### ISSUE TITLE
Issue with process_data.R script

### ISSUE THREAD

**Issue by hadleyd2** [STAT547-UBC-2019-20/group_09#25]
Hello @kristinawright ,

I believe I found an issue with the process_data.R script.

Right now, the cleaned data excludes the largest price listings beyond 500 euros. The correlogram and violin plots are based on all listings, not the first 0.975 quantile of listings.

Am working on this now and will send you a pull request when it is completed.

Thanks!
-Dan

**Comment by kristinawright** [comment]
I completed the EDA excluding the largest price listings beyond 500 euros.  I just sent a pull request.

**Comment by hadleyd2** [comment]
Hello @kristinawright,

Just sent a pull request for you to review this change. Can you please confirm?

Thanks!
-Dan

**Comment by kristinawright** [comment]
confirmed.  I will redo the EDA script with the update

**Comment by hadleyd2** [comment]
Thanks so much and sorry for not picking this error up earlier!

If you have any trouble (especially with the price density plots or new cleaned dataset), please feel free to open another issue and I can look into it.
