### ISSUE TITLE
Milestone 03

### ISSUE THREAD

**Issue by hadleyd2** [STAT547-UBC-2019-20/group_09#35]
Hello @kristinawright,

In this [PR](https://github.com/STAT547-UBC-2019-20/group_09/pull/34), I have done most of the required work up to and including Task 3. However, I have not yet added Makefile documentation to our repo's README, and I'm probably missing other small changes. Hopefully, when you review this pull request and the associated changes you could have a look at some of this stuff for me?

Please note that I moved some files around:

  - I am now saving images directly to our `images` folder and not within subfolders for each milestone. I talked to Firas about this and he said we can always overwrite stuff as our tagged releases can be used to view our repo for any particular milestone.

  - I have scripts for knitting our final report, `knit.R`, and running a very simple linear regression, saving a QQ-plot, and saving a linear model object, `lm.R`. The usage section our project README is updated to reflect this.

  - I renamed our scripts to give them shorter names and updated the README file accordingly.

  - Make file is is in the main project repo, but instructions are not given in the README. However, you should be able to run `make all` to reproduce the analysis and `make clean` to clean up the dependencies. Let me know if anything is unclear.

  - Our final report is now being knitted from `docs/final_report.Rmd`. Please edit this file going forward for our changes to the final report.

Let me know if anything is unclear or if you have issues running anything. Also, can you please give me an indication of when you will have time to work on milestone 03? My weekends are usually quite busy with family obligations, but I would like to try and plan to be available when you are going to work on the milestone in case you need me.

Thanks!
-Dan

**Comment by kristinawright** [comment]
Hi @hadleyd2 ,

I am working on the project now.  I will review your work and start on Task 4.

Kristina

**Comment by hadleyd2** [comment]
Hello @kristinawright,

Sounds good! I am available if you need me. I also noticed a typo in my original issue. The first bullet point should read, "I am NOW saving images..."

Sorry for any confusion!
-Dan

**Comment by kristinawright** [comment]
Hey @hadleyd2 ,

I made a pull request for my work.  I have:
-edited the final report Rmd to fix the images sizes so they don't get cut off the page
-finished writing the final report (methods, discussion).  I was not quite sure how to interpret the results, so I wrote something for the discussion, but I did not make a thorough assessment.
-I edited the Readme to include instructions of running make

I looked over you work and it looks good!  All the scripts ran for me without issue.

Kristina

**Comment by hadleyd2** [comment]
hello @kristinawright 

I just tagged a [release](https://github.com/STAT547-UBC-2019-20/group_09/releases/tag/v3.0) and submitted to canvas. Please feel free to make any changes if there's something I missed or something that could be better. 

Let me know if you have any questions or comments.

Thanks!
-Dan
